# Generated by Django 3.2.15 on 2022-11-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_toy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='toy',
            old_name='category',
            new_name='toy_category',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='price',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='toy',
            name='sub_category',
        ),
    ]
